import { PinInput, Stack, Text, Title } from '@mantine/core';
import { useIntl } from 'react-intl';

import { useThemeColors } from '@/theme/useThemeColors.ts';

export const GoogleAuth = () => {
  const { formatMessage } = useIntl();
  const { rcc } = useThemeColors();

  return (
    <Stack gap={24}>
      <Stack gap={8} align="center">
        <Title size="xl" c={rcc('regular-content.primary')}>
          {formatMessage({
            id: 'widget.google_auth.title',
            defaultMessage: 'Enter Google Authenticator code',
          })}
        </Title>
        <Text size="lg" c={rcc('regular-content.secondary')}>
          {formatMessage({
            id: 'widget.google_auth.subtitle',
            defaultMessage:
              'Please enter the 6-digit code generated by Google Authenticator to continue',
          })}
        </Text>
      </Stack>
      <PinInput />
    </Stack>
  );
};
